[build]
  command = "npm run build"  # Build command
  publish = "build"          # Publish directory

[dev]
  command = "npm start"      # Command to start the development server
  targetPort = 3000          # Port where your app runs locally
  port = 3001                # Port for Netlify Dev proxy